services:
  webapp:
    build: .
    ports:
      - "8081:8080"
    environment:
      - ROOT_PATH=/host/downloads
    volumes:
      - type: bind
        source: C:\Users\{user}\Downloads
        target: /host/downloads